export const products = [
  {
    id: "mug",
    name: "Stoneware mug",
    price: 28,
    was: 35,
    sold: 214,
    category: "table",
    image: "/public/products/mug.jpg",
    blurb: "A heavy everyday cup. Holds heat, sits steady.",
    detail: "Thrown in small batches. Dishwasher safe. 320ml.",
  },
  {
    id: "napkins",
    name: "Linen napkin set",
    price: 36,
    was: 45,
    sold: 88,
    category: "table",
    image: "/public/products/napkins.jpg",
    blurb: "Four washed-linen napkins. Soft from the first wash.",
    detail: "Natural flax. 42cm square. Set of four.",
  },
  {
    id: "skillet",
    name: "Cast iron skillet",
    price: 84,
    was: 110,
    sold: 61,
    category: "kitchen",
    image: "/public/products/skillet.jpg",
    blurb: "One pan for eggs, bread, and Sunday chicken.",
    detail: "26cm. Pre-seasoned. Oven safe to 260°C.",
  },
  {
    id: "board",
    name: "Oak cutting board",
    price: 54,
    was: 68,
    sold: 73,
    category: "kitchen",
    image: "/public/products/board.jpg",
    blurb: "End-grain oak. Kind to knives, built to last.",
    detail: "40 × 28cm. Food-safe oil finish.",
  },
  {
    id: "bowl",
    name: "Serving bowl",
    price: 32,
    was: 40,
    sold: 156,
    category: "table",
    image: "/public/products/bowl.jpg",
    blurb: "Wide enough for salad, deep enough for stew.",
    detail: "Speckled glaze. 24cm across.",
  },
  {
    id: "candles",
    name: "Beeswax tapers",
    price: 22,
    was: 28,
    sold: 190,
    category: "care",
    image: "/public/products/candles.jpg",
    blurb: "A pair of tapers. Slow burn, clean scent.",
    detail: "Two candles. About 8 hours each.",
  },
  {
    id: "soap",
    name: "Olive oil soap",
    price: 12,
    was: 16,
    sold: 340,
    category: "care",
    image: "/public/products/soap.jpg",
    blurb: "A simple bar for the sink. No perfume.",
    detail: "Cold-pressed olive oil. 120g.",
  },
  {
    id: "throw",
    name: "Wool throw",
    price: 96,
    was: 120,
    sold: 42,
    category: "care",
    image: "/public/products/throw.jpg",
    blurb: "A dense wool blanket for the sofa or the end of the bed.",
    detail: "130 × 180cm. Undyed merino.",
  },
  {
    id: "pitcher",
    name: "Stoneware pitcher",
    price: 38,
    was: 48,
    sold: 97,
    category: "table",
    image: "/public/products/pitcher.svg",
    blurb: "Water or wine for the table. A steady pour.",
    detail: "1.2L. Chip-resistant glaze.",
  },
  {
    id: "tumblers",
    name: "Glass tumbler set",
    price: 26,
    was: 32,
    sold: 141,
    category: "table",
    image: "/public/products/tumblers.svg",
    blurb: "Four short glasses. Clear, heavy base.",
    detail: "Set of four. 280ml each.",
  },
  {
    id: "vase",
    name: "Bud vase",
    price: 18,
    was: 24,
    sold: 203,
    category: "table",
    image: "/public/products/vase.svg",
    blurb: "One stem or a small bunch. Quiet on a shelf.",
    detail: "15cm. Recycled glass.",
  },
  {
    id: "mats",
    name: "Linen placemats",
    price: 29,
    was: 36,
    sold: 76,
    category: "table",
    image: "/public/products/mats.svg",
    blurb: "A set of four. Soften a bare table.",
    detail: "Natural flax. Set of four.",
  },
  {
    id: "tray",
    name: "Oak serving tray",
    price: 44,
    was: 55,
    sold: 58,
    category: "table",
    image: "/public/products/tray.svg",
    blurb: "Breakfast in, or drinks out. Handles that fit a hand.",
    detail: "46 × 30cm. Oil finish.",
  },
  {
    id: "oil",
    name: "Olive oil cruet",
    price: 24,
    was: 30,
    sold: 112,
    category: "kitchen",
    image: "/public/products/oil.svg",
    blurb: "A narrow pour for the board or the pan.",
    detail: "350ml glass. Cork stopper.",
  },
  {
    id: "salt",
    name: "Salt cellar",
    price: 16,
    was: 20,
    sold: 188,
    category: "kitchen",
    image: "/public/products/salt.svg",
    blurb: "Pinch salt by the stove. Lid keeps it dry.",
    detail: "Stoneware. 8cm wide.",
  },
  {
    id: "apron",
    name: "Linen apron",
    price: 34,
    was: 42,
    sold: 69,
    category: "kitchen",
    image: "/public/products/apron.svg",
    blurb: "Cross-back, deep pocket. Washes soft.",
    detail: "Natural flax. One size.",
  },
  {
    id: "rest",
    name: "Spoon rest",
    price: 14,
    was: 18,
    sold: 225,
    category: "kitchen",
    image: "/public/products/rest.svg",
    blurb: "Keeps the spoon off the hob.",
    detail: "Speckled glaze. Dishwasher safe.",
  },
  {
    id: "kettle",
    name: "Stovetop kettle",
    price: 48,
    was: 62,
    sold: 81,
    category: "kitchen",
    image: "/public/products/kettle.svg",
    blurb: "Whistles when ready. Steel, not plastic.",
    detail: "1.5L. Fits a gas or induction hob.",
  },
  {
    id: "basket",
    name: "Woven basket",
    price: 42,
    was: 52,
    sold: 54,
    category: "care",
    image: "/public/products/basket.svg",
    blurb: "Throws, kindling, or a weekend shop.",
    detail: "Seagrass. 40cm wide.",
  },
  {
    id: "lotion",
    name: "Hand lotion",
    price: 15,
    was: 19,
    sold: 276,
    category: "care",
    image: "/public/products/lotion.svg",
    blurb: "Unscented cream for dry hands.",
    detail: "120ml. Pump bottle.",
  },
  {
    id: "diffuser",
    name: "Reed diffuser",
    price: 28,
    was: 36,
    sold: 93,
    category: "care",
    image: "/public/products/diffuser.svg",
    blurb: "A light cedar note. No flame.",
    detail: "100ml. Lasts about eight weeks.",
  },
  {
    id: "hook",
    name: "Oak coat hook",
    price: 22,
    was: 28,
    sold: 134,
    category: "care",
    image: "/public/products/hook.svg",
    blurb: "A double hook for the hall.",
    detail: "Solid oak. Screws included.",
  },
];

export const categories = [
  { id: "all", label: "All" },
  { id: "kitchen", label: "Kitchen" },
  { id: "table", label: "Table" },
  { id: "care", label: "Home & care" },
];

export function money(value) {
  return `£${value.toFixed(2)}`;
}

export function findProduct(id) {
  return products.find((item) => item.id === id);
}
